version: '3'
services:
  app:
    build: .
    ports:
     - "80:80"
  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server --appendonly yes
    volumes:
        - ./data:/data



