version: '3'
services:
  shrtnr_app:
    image: shrtnr-api
    build: .
    ports:
     - "80:80"
    networks:
     - mynet
    depends_on:
      - shrtnr_redis
  shrtnr_redis:
    image: "redis:alpine"
    restart: always
    command: redis-server --appendonly yes
    networks:
      - mynet    
    volumes:
        - ./data:/data

networks:
  mynet:    

